name: ECS CICD

on:
  workflow_dispatch:

jobs:
  ecs-cicd:
   runs-on: ubuntu-latest

   steps:
##setup
   - name: Checkout repository
     uses: actions/checkout@v2

##### CODE CI

## TF CD
   - name: Set up Terraform
     uses: hashicorp/setup-terraform@v1


   - name: Configure AWS credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # or hardcode us-east-1
        

##CD
   - name: Initialize Terraform
     run: terraform init
     
   - name: Terraform Plan
     run: terraform plan -var="app=lambda"

   - name: Terraform Apply
     run: terraform apply --auto-approve -var="app=lambda"